services:
  resume:
    image: resume-site:0.0.1
    build:
      context: .
      dockerfile: Dockerfile
    container_name: resume-site
    restart: unless-stopped
    ports:
      - "3006:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000

    volumes:
      - ./public:/app/public:ro

    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s
